/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmc.minecraft;


import java.io.IOException;
import jmc.minecraft.utils.ConfigLoaderCore;
import jmc.minecraft.TexturedPanel;
import jmc.minecraft.utils.GlobalVar;
import jmc.minecraft.utils.Utils;
import jmc.minecraft.Options;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
//import javax.swing.JEditorPane;

/**
 *
 * @author DimanA90
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        panelNews = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EditorPaneNews = new javax.swing.JEditorPane();
        panelControls = new TexturedPanel();
        LabelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        CheckBoxSave = new javax.swing.JCheckBox();
        ButtonLogin = new javax.swing.JButton();
        ButtonSetting = new javax.swing.JButton();
        ButtonAddons = new javax.swing.JButton();
        LabelStatus = new javax.swing.JLabel();
        ComboBoxSelectClient = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPaneClientInfo = new javax.swing.JTextPane();
        LabelRegistration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(GlobalVar.MainWndTitle);
        setName("MainWindow"); // NOI18N

        PanelMain.setLayout(new javax.swing.BoxLayout(PanelMain, javax.swing.BoxLayout.LINE_AXIS));

        panelNews.setBackground(new java.awt.Color(204, 204, 204));

        EditorPaneNews.setEditable(false);
        EditorPaneNews.setBorder(null);
        EditorPaneNews.setContentType("text/html"); // NOI18N
        EditorPaneNews.setText("<html><body><font color=\\\"#808080\\\"><br><br><br><br><br><br><br><center>Loading update news..</center></font></body></html>");
        jScrollPane2.setViewportView(EditorPaneNews);
        EditorPaneNews.addHyperlinkListener(new HyperlinkListener() {
            public void hyperlinkUpdate(HyperlinkEvent he) {
                if (he.getEventType() == HyperlinkEvent.EventType.ACTIVATED)
                try {
                    Utils.openLink(he.getURL().toURI());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        new Thread() {
            public void run() {
                try {
                    EditorPaneNews.setPage(new URL(GlobalVar.NewsURL));
                } catch (Exception e) {
                    e.printStackTrace();
                    EditorPaneNews.setText("<html><body><font color=\"#808080\"><br><br><br><br><br><br><br><center>Failed to update news<br></center></font></body></html>");
                }
            }
        }
        .start();

        javax.swing.GroupLayout panelNewsLayout = new javax.swing.GroupLayout(panelNews);
        panelNews.setLayout(panelNewsLayout);
        panelNewsLayout.setHorizontalGroup(
            panelNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        panelNewsLayout.setVerticalGroup(
            panelNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        PanelMain.add(panelNews);

        panelControls.setBackground(new java.awt.Color(204, 204, 204));
        panelControls.setToolTipText("");

        LabelUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsername.setText("Логин:");
        LabelUsername.setFocusable(false);

        labelPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Пароль:");
        labelPassword.setFocusable(false);

        textFieldUsername.setText(GlobalVar.userName);

        PasswordField.setText(GlobalVar.password);

        CheckBoxSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckBoxSave.setForeground(new java.awt.Color(255, 255, 255));
        CheckBoxSave.setText("Запомнить");
        CheckBoxSave.setToolTipText("");
        CheckBoxSave.setOpaque(false);

        ButtonLogin.setText("Играть");

        ButtonSetting.setText("Настройки");
        ButtonSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSettingMouseClicked(evt);
            }
        });

        ButtonAddons.setText("Дополнения");

        LabelStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelStatus.setForeground(new java.awt.Color(255, 0, 0));
        LabelStatus.setText("Статус:");
        LabelStatus.setFocusable(false);
        LabelStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ComboBoxSelectClient.setMaximumRowCount(16);
        ComboBoxSelectClient.setModel(new javax.swing.DefaultComboBoxModel(GlobalVar.ClientNames));
        ComboBoxSelectClient.setSelectedIndex(GlobalVar.CurrentServer);
        ComboBoxSelectClient.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxSelectClientItemStateChanged(evt);
            }
        });

        TextPaneClientInfo.setEditable(false);
        TextPaneClientInfo.setBorder(null);
        TextPaneClientInfo.setContentType("text/html"); // NOI18N
        TextPaneClientInfo.setText("<html>"+GlobalVar.clientinfo+"</html>");
        jScrollPane1.setViewportView(TextPaneClientInfo);

        LabelRegistration.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelRegistration.setForeground(new java.awt.Color(153, 255, 102));
        LabelRegistration.setText("Бесплатная регистрация");
        LabelRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelRegistrationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelControlsLayout = new javax.swing.GroupLayout(panelControls);
        panelControls.setLayout(panelControlsLayout);
        panelControlsLayout.setHorizontalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelControlsLayout.createSequentialGroup()
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelUsername)
                            .addComponent(labelPassword))
                        .addGap(18, 18, 18)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField)
                            .addComponent(textFieldUsername)))
                    .addComponent(ComboBoxSelectClient, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelControlsLayout.createSequentialGroup()
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxSave))
                        .addGap(18, 18, 18)
                        .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAddons, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(ButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(panelControlsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelRegistration)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelControlsLayout.setVerticalGroup(
            panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUsername)
                    .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelRegistration)
                .addGap(9, 9, 9)
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLogin)
                    .addComponent(CheckBoxSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSetting)
                    .addComponent(ButtonAddons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxSelectClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelMain.add(panelControls);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxSelectClientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxSelectClientItemStateChanged
        // TODO add your handling code here:
        GlobalVar.CurrentServer = ComboBoxSelectClient.getSelectedIndex();
        ConfigLoaderCore cfs = new ConfigLoaderCore();
        cfs.LoadClientConfig(GlobalVar.itemsServers[GlobalVar.CurrentServer]);

        TextPaneClientInfo.setText("<html>"+GlobalVar.clientinfo+"</html>");  //Set new client info
    }//GEN-LAST:event_ComboBoxSelectClientItemStateChanged

    private void ButtonSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSettingMouseClicked
        // TODO add check created
        Options opt = new Options();
        opt.view();
    }//GEN-LAST:event_ButtonSettingMouseClicked

    private void LabelRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelRegistrationMouseClicked
        // TODO add your handling code here:
        try {
              Utils.openLink(new URL(GlobalVar.RegURL).toURI());
            } catch (Exception e) {
              e.printStackTrace();
            }
    }//GEN-LAST:event_LabelRegistrationMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) throws ClassNotFoundException {
        

             /*
             * Load core config
             */
        ConfigLoaderCore cf = new ConfigLoaderCore();
        cf.loadCoreConfig();  //Load core properties
        cf.LoadUserConfig(); //Load user config
        cf.LoadClientConfig(GlobalVar.itemsServers[GlobalVar.CurrentServer]);//Load first info about client
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (InstantiationException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddons;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JButton ButtonSetting;
    private javax.swing.JCheckBox CheckBoxSave;
    private javax.swing.JComboBox ComboBoxSelectClient;
    private javax.swing.JEditorPane EditorPaneNews;
    private javax.swing.JLabel LabelRegistration;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPasswordField PasswordField;
    public javax.swing.JTextPane TextPaneClientInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelControls;
    private javax.swing.JPanel panelNews;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables
}
/*
*Чтение инфы о клиента и списка дополнений с описанием
*Передаем в функцию имяклиента(индексвыбора)
* читаем имяклиента.yml
* создаем поток и отображаем инфу как html страничку
*---------------
* дополнения оставим напотом
 */