info: <body text="#333333" border bgcolor="#cccccc" ><center><p><font size="5">Класический майнкрафт.</font><br/><small><font color="#CC0000">Версия 1.6.2</font></small></p><p><strong>Без модов.</strong></p></center></body>
oldminecraft: false
addons: 
       - none
addonsinfo:
       - none
archivesList:
- bin.zip
- content.zip